### PR TITLE
Fix dqn

### PR DESCRIPTION
**Pull request by Mostafa95**
When loading a model, network_structure is stored in "network_layers" var , so when saving a new model, error occurs in line 
                      `  parameter_values = [epochs, steps, updateTargetNetwork, explorationRate, minibatch_size, learnStart, learningRate, discountFactor, memorySize, network_inputs, network_outputs, network_structure, epoch]`
as "network_structure" var is not defined.

Also  updated README.md .

### CODE REVIEW

**Comment by mkhansen-intel** [comment]
@Mostafa95 - I saw this problem too, glad you're submitting a PR to fix it. Have you seen issue #121 that I filed, which is that the number of inputs should be = 20?

**Comment by Mostafa95** [comment]
Yeah, I don't know why that happened to you, I traced back to file 
`gym-gazebo/gym_gazebo/envs/turtlebot/gazebo_circuit2_turtlebot_lidar_nn.py  `
in reset function and printed data.ranges and it's a 100. Did you run turtlebot_nn_setup.bash ?

**Comment by mkhansen-intel** [comment]
@Mostafa95 - OK, I see the issue now. I was running the other setup file: turtlebot_setup.bash. The difference appears to be that in the kobuki.urdf.xacro file for the 'nn' version it sets ray_count_horizontal = "200" instead of "40".   When I ran the right setup file, it now works. Thanks!

**Comment by vmayoral** [comment]
Thanks for the ping @mkhansen-intel.

**Comment by mkhansen-intel** [comment]
@vmayoral - no problem, happy to help. BTW I'm going to submit a PR to fix #120 and I have some other code cleanup fixes I'd like to submit too. What's the status of the Travis CI? I see that it failed for this PR, is the CI broken?

**Comment by vmayoral** [comment]
> is the CI broken?

Yes it is. AFAIK, none of us have put time into it for a while. Help with that would be very welcome.

**Comment by mkhansen-intel** [comment]
@Mostafa95 @vmayoral @rkojcev - it looks like this PR and my PR #120 were wiped out by the latest changes to master. I'll rebase and re-submit my PR, you will want to do the same.

**Pull request merged**
